# rustfmt sucks right now. It doesn't give me enough control over certain things, and some items which are supported are only available in unstable.
# I'm putting this here so that some future contributor who has it turned on by default doesn't accidentally reformat my code while trying to fix this.
disable_all_formatting = true
