# to run rustfmt use `rustfmt +nightly <filename> --edition 2024` or `cargo +nightly fmt` (the former if you want to format a specific filename

# rustfmt sucks right now. It doesn't give me enough control over certain things. Also,
# Some examples:
# - removed blank lines after items before closing braces for the mod block.
# - removed a blank line I want to have between the implementation and the first item, despite setting for 'blank_lines_upper_bound' and 'blank_lines_lower_bound'
# - removed blank line at the end of a function.
# - I want the "Visual" indent_style for function calls, arrays, tuples, and control flow, but I want "Block" for structs, and there's no option to do that.
# - Despite having struct_lit_single_line set to false, it still changed a struct in an enum variant to single line.
# - It inserted spaces so that comments at the end of some match arms are left aligned. There is no configuration for this.
# - It should not "rewrap" lines where I've already placed a line-break. There might be a reason I put it there and not where rustfmt wants to.
# - It's not a set it and forget it because I can never be sure that it's going to do something unexpected.
# - modules should be sorted only alphabetically. They should be sorted by dependency first, so the more independent ones are at the top and
#   dependent ones are always below the ones they are dependent on (unless there's a circular dependency, in which case there should be a warning)
max_width = 200
fn_params_layout = "Compressed"
match_block_trailing_comma = true
brace_style = "PreferSameLine"
indent_style = "Visual"
trailing_comma = "Never"
use_field_init_shorthand = true
use_small_heuristics = "Max"
imports_granularity = "One"
# TODO: Turn this back on once I'm sure about rustfmt configuration.
reorder_imports = false
single_line_if_else_max_width = 0
single_line_let_else_max_width = 0
struct_lit_single_line = false
struct_lit_width = 0
struct_variant_width = 0
reorder_modules = false
