[package]
name = "elbie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
csv = "1.2.2"
unicode-width = "0.1.10"
pad = "0.1.6"
